### ISSUE TITLE
Integrate with popular NuGet packages for parsing command line

### ISSUE THREAD

**Issue by Athari** [Athari/CsConsoleFormat#17]
Integrate with popular command-line parsers to allow:

1. Zero-effort improvement to formatting of help texts. Should match the original tool's formatting closely, but improve upon it.

2. Easy customization options like colors, offsets, headers, padding etc.

3. Deep customization by providing source data in a ready-to-use form if the original tool doesn't. Code for generating documents from the points above should serve as a sample in this case.

Likely candidates:

* [ ] [CommandLineParser](https://github.com/commandlineparser/commandline) — by far the most popular, supporting both major versions may be a good idea
* [ ] [FluentCommandLineParser](https://github.com/fclp/fluent-command-line-parser) — popular library
* [ ] [PowerArgs](https://github.com/adamabdelhamed/PowerArgs) — popular library
* [ ] [System.CommandLine](https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine) — part of Core FX Lab, from Microsoft
* [ ] [CommandLineUtils](https://github.com/natemcmaster/CommandLineUtils) — originally from Microsoft ASP.NET MVC, currently maintained by another developer

Evaluate command line packages:

* https://www.nuget.org/packages?q=command+line
* http://nugetmusthaves.com/Package?q=command+line
* https://github.com/quozd/awesome-dotnet#cli

**Comment by drewnoakes** [comment]
Check out [`System.CommandLine` from the corefxlab](https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine). There's a chance it might become the built-in way to do this for .NET.

**Comment by Athari** [comment]
@drewnoakes Is it available as a NuGet package? I can't find it. It has some limitations and questionable implementation in a few places, but I like its API. If it isn't available on NuGet though, I can't support it in a sensible way. It's also been [in CoreFXLabs for 3 years](https://github.com/dotnet/corefxlab/commit/d04d844e76d9a9b192725e4eb8dfc1cd7a057ab6) already, which isn't promising.

**Comment by drewnoakes** [comment]
I'm not associated with the project and know as much as you. Only thought you might like to look at it as well as those in your list.

**Comment by fedarovich** [comment]
One more nice command line parsing package for .Net Standard: [https://github.com/natemcmaster/CommandLineUtils](https://github.com/natemcmaster/CommandLineUtils)
